version: '3.1'

services:
  mongo:
    image: zcube/bitnami-compat-mongodb:6.0
    restart: unless-stopped
    ports:
      - '27017:27017'
    environment:
      MONGODB_ADVERTISED_HOSTNAME: 127.0.0.1
      MONGODB_REPLICA_SET_MODE: primary
      MONGODB_REPLICA_SET_NAME: rs0
      MONGODB_REPLICA_SET_KEY: replicasetkey123
      MONGODB_ROOT_USER: root
      MONGODB_ROOT_PASSWORD: password
  redis:
    image: redis:alpine
    restart: unless-stopped
    ports:
      - '6379:6379'
    environment:
      ALLOW_EMPTY_PASSWORD: 'yes'
      REDIS_HOST: ${REDIS_HOST:-}
      REDIS_PORT: ${REDIS_PORT:-6379}
