/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'

// Create Virtual Routes

const IndexLazyImport = createFileRoute('/')()
const UsersIndexLazyImport = createFileRoute('/users/')()
const PostsIndexLazyImport = createFileRoute('/posts/')()
const UsersRegisterLazyImport = createFileRoute('/users/register')()
const UsersProfileLazyImport = createFileRoute('/users/profile')()
const UsersLoginLazyImport = createFileRoute('/users/login')()
const PostsNewLazyImport = createFileRoute('/posts/new')()

// Create/Update Routes

const IndexLazyRoute = IndexLazyImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

const UsersIndexLazyRoute = UsersIndexLazyImport.update({
  path: '/users/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/users/index.lazy').then((d) => d.Route))

const PostsIndexLazyRoute = PostsIndexLazyImport.update({
  path: '/posts/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/posts/index.lazy').then((d) => d.Route))

const UsersRegisterLazyRoute = UsersRegisterLazyImport.update({
  path: '/users/register',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/users/register.lazy').then((d) => d.Route),
)

const UsersProfileLazyRoute = UsersProfileLazyImport.update({
  path: '/users/profile',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/users/profile.lazy').then((d) => d.Route))

const UsersLoginLazyRoute = UsersLoginLazyImport.update({
  path: '/users/login',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/users/login.lazy').then((d) => d.Route))

const PostsNewLazyRoute = PostsNewLazyImport.update({
  path: '/posts/new',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/posts/new.lazy').then((d) => d.Route))

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/posts/new': {
      preLoaderRoute: typeof PostsNewLazyImport
      parentRoute: typeof rootRoute
    }
    '/users/login': {
      preLoaderRoute: typeof UsersLoginLazyImport
      parentRoute: typeof rootRoute
    }
    '/users/profile': {
      preLoaderRoute: typeof UsersProfileLazyImport
      parentRoute: typeof rootRoute
    }
    '/users/register': {
      preLoaderRoute: typeof UsersRegisterLazyImport
      parentRoute: typeof rootRoute
    }
    '/posts/': {
      preLoaderRoute: typeof PostsIndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/users/': {
      preLoaderRoute: typeof UsersIndexLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexLazyRoute,
  PostsNewLazyRoute,
  UsersLoginLazyRoute,
  UsersProfileLazyRoute,
  UsersRegisterLazyRoute,
  PostsIndexLazyRoute,
  UsersIndexLazyRoute,
])

/* prettier-ignore-end */
